name: training
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - rdkit
  - pandas
  - numpy<2.0
  - tqdm
  - scikit-learn
  - pip
  - pip:
    - torch_geometric
    - pyg_lib
    - torch_scatter
    - torch_sparse
    - torch_cluster
    - torch_spline_conv
    - --find-links https://data.pyg.org/whl/torch-2.1.2+cu118.html
